sudo: false
language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: Z9/9ChwFmQZp1b/os9rtENq5dTq1kO+mja6/h/purGhTS391h3zT40xfTR/MizGDk76HelOBshAdi98jhyMA5ooIBX2823v7rN8K5h2lQ4w/XNrTYp3PpGIwPT7jcDlTiDdIZFzNFwAXbkStxjFx3nhvgsU9bBkFVRyNzBPNYas=
  app: hacksi
  on:
    repo: HackSI/site
notifications:
  slack: hacksi:4lnHm1RjO4yfojtzgjWXMxeZ
